#183 - Added environment field to function model, deleted migrations
beer-garden/functionary pull request #187
Opened 2023-01-27 14:02 UTC by xeonneon

Closes #183 

## Introduced Changes
- Added environment foreign key field to Function model
- Added three indexes to the Function model
- Added clean method to Function model to ensure the Function's environment is equivalent to it's package environment
- Replaced previous `package__environment` queries to just check the Function's environment field instead
- Removed all migrations in favor of only generating migration files for Functionary releases
- Updated .gitignore to ignore migration files
- Updated migration task to also makemigrations

## Testing
- I would recommend deleting your existing postgresql docker volume and using the updated migration task to test out this PR. 
- Ensure all previous functionality still works, such as creating tasks, task parameters rendering, etc.

2023-01-27 14:45 UTC, xeonneon commented
Note: I had to also update the github actions to makemigrations when running the functionary unit tests

2023-01-27 21:00 UTC, scott-taubman requested changes

2023-01-30 13:38 UTC, xeonneon commented on functionary/core/models/function.py
> +            models.Index(fields=["environment", "id"], name="function_environment_id"),
Fixed. I had added that index since I saw we had a query that was looking up functions based on environment and id

2023-01-30 13:39 UTC, xeonneon commented on functionary/core/models/function.py
> +                fields=["environment", "package"], name="function_environment_package"
Fixed in both models

2023-01-30 15:06 UTC, scott-taubman approved these changes

2023-01-30 15:06 UTC, merged