#184 - __str__ now returns the display_name if set
beer-garden/functionary pull request #188
Opened 2023-01-27 17:14 UTC by xeonneon

Closes #184 

## Introduced Changes
- Updated Function and Package `__str__` method to return the `display_name` if it is set. Otherwise, return the `name`
  - This allows for the `name` and `display_name` to continue to exist as implemented. The templates just need to print out the `Function` or `Package` instead of the `name` or `display_name` attributes
- Updated the templates to display the `Function` or `Package` rather than the `name` or `display_name` attributes
- Removed some unnecessary `name` and `display_name` checks for teams and environments 

## Testing
Just need to visit the Function, Package, and Task views and verify the `Function` and `Package` names are still being displayed

2023-01-27 20:14 UTC, scott-taubman requested changes
I don't love using `__str__` for this.  To me, it makes for some ambiguity when reading code that leverages it.  For example:

```python
 <span>{{ task.function }}</span>
```

Knowing that `task.function` is an object, what am I expecting to be rendered here?  Not even specifically, but generally?  Could be the id, the name, the `__repr__`...I basically have to go look at the `__str__` implementation to have any clue.  Or even to have confidence that thing that will get displayed matches the intent.

I think having a clearly defined property method makes both the intent and the expected outcome more clear to a reader.

Also, in at least one case here (the change to `utils/tasking.py`) you'd have to call `str()` to ensure the same behavior as before, and again `task.function.display_name` (or whatever the property method is called) feels more explicit than `str(task.function)`.

2023-01-27 22:46 UTC, scott-taubman requested changes

2023-01-27 22:46 UTC, scott-taubman commented on functionary/ui/templates/core/environment_detail.html
> +                            <a href="{% url 'ui:package-detail' package.id %}">{{ package }}</a>
missed a `package.render_name` here.

2023-01-30 13:38 UTC, xeonneon commented on functionary/ui/templates/core/environment_detail.html
> +                            <a href="{% url 'ui:package-detail' package.id %}">{{ package }}</a>
Fixed

2023-01-30 15:26 UTC, scott-taubman approved these changes

2023-01-30 17:20 UTC, merged